cluster:
  name: "confluent-community-${ENVIRONMENT}-cluster"
  version: "8.0.0"
  
servers:
  - hostname: "kafka-${ENVIRONMENT}-node-1"
    ip: "192.168.1.10"
    node_id: 1
    broker_id: 1
  - hostname: "kafka-${ENVIRONMENT}-node-2"
    ip: "192.168.1.11"
    node_id: 2
    broker_id: 2
  - hostname: "kafka-${ENVIRONMENT}-node-3"
    ip: "192.168.1.12"
    node_id: 3
    broker_id: 3

credentials:
  ssh_user: "root"
  ssh_key_path: "~/.ssh/kafka_test_key"
  kafka_user: "kafka"
  kafka_group: "kafka"

network:
  plaintext_port: 9092
  controller_port: 9093
  kafka_ui_port: 8080

storage:
  data_dir: "/kafka"
  log_dir: "/var/log/confluent"

installation:
  local_files_path: "/tmp/files"
  confluent_archive: "confluent-community-8.0.0.zip"
  kafka_ui_jar: "provectus-kafka-ui.jar"
  java_archive: "openjdk-11.0.2.tar.gz"

defaults:
  partitions_per_topic: 24
  retention_hours: 24
  segment_retention_hours: 1
  replication_factor: 3
  min_insync_replicas: 2
  auto_create_topics: false
  max_servers: 3