services:
  kafka-test-node1:
    image: registry.access.redhat.com/ubi8/ubi:latest
    hostname: kafka-test-node1
    container_name: kafka-test-node1
    networks:
      servers-net:
        ipv4_address: 192.168.1.10
    ports:
      - "2221:22"
      - "9092:9092"
      - "9093:9093"
    extra_hosts:
      - "kafka-test-node1:192.168.1.10"
      - "kafka-test-node2:192.168.1.11"
      - "kafka-test-node3:192.168.1.12"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      - SSH_USER=admin
      - SSH_PASSWORD=password123
    command: >
      bash -c "
        dnf update -y &&
        dnf install -y openssh-server sudo passwd hostname util-linux procps-ng unzip tar gzip &&
        ssh-keygen -A &&
        useradd -m -s /bin/bash admin &&
        echo 'admin:password123' | chpasswd &&
        echo 'root:rootpassword' | chpasswd &&
        usermod -aG wheel admin &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config &&
        /usr/sbin/sshd &&
        tail -f /dev/null
      "

  kafka-test-node2:
    image: registry.access.redhat.com/ubi8/ubi:latest
    hostname: kafka-test-node2
    container_name: kafka-test-node2
    networks:
      servers-net:
        ipv4_address: 192.168.1.11
    ports:
      - "2222:22"
      - "9094:9092"
      - "9095:9093"
    extra_hosts:
      - "kafka-test-node1:192.168.1.10"
      - "kafka-test-node2:192.168.1.11"
      - "kafka-test-node3:192.168.1.12"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      - SSH_USER=admin
      - SSH_PASSWORD=password123
    command: >
      bash -c "
        dnf update -y &&
        dnf install -y openssh-server sudo passwd hostname util-linux procps-ng unzip tar gzip &&
        ssh-keygen -A &&
        useradd -m -s /bin/bash admin &&
        echo 'admin:password123' | chpasswd &&
        echo 'root:rootpassword' | chpasswd &&
        usermod -aG wheel admin &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config &&
        /usr/sbin/sshd &&
        tail -f /dev/null
      "

  kafka-test-node3:
    image: registry.access.redhat.com/ubi8/ubi:latest
    hostname: kafka-test-node3
    container_name: kafka-test-node3
    networks:
      servers-net:
        ipv4_address: 192.168.1.12
    ports:
      - "2223:22"
      - "9096:9092"
      - "9097:9093"
    extra_hosts:
      - "kafka-test-node1:192.168.1.10"
      - "kafka-test-node2:192.168.1.11"
      - "kafka-test-node3:192.168.1.12"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      - SSH_USER=admin
      - SSH_PASSWORD=password123
    command: >
      bash -c "
        dnf update -y &&
        dnf install -y openssh-server sudo passwd hostname util-linux procps-ng unzip tar gzip &&
        ssh-keygen -A &&
        useradd -m -s /bin/bash admin &&
        echo 'admin:password123' | chpasswd &&
        echo 'root:rootpassword' | chpasswd &&
        usermod -aG wheel admin &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config &&
        /usr/sbin/sshd &&
        tail -f /dev/null
      "

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    hostname: kafka-ui
    container_name: kafka-ui
    networks:
      servers-net:
        ipv4_address: 192.168.1.20
    ports:
      - "8080:8080"
    extra_hosts:
      - "kafka-test-node1:192.168.1.10"
      - "kafka-test-node2:192.168.1.11"
      - "kafka-test-node3:192.168.1.12"
    environment:
      KAFKA_CLUSTERS_0_NAME: "kafka-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-test-node1:9092,kafka-test-node2:9092,kafka-test-node3:9092"
      KAFKA_CLUSTERS_0_READONLY: "false"
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - kafka-test-node1
      - kafka-test-node2
      - kafka-test-node3
    restart: unless-stopped

networks:
  servers-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
